services:
  app:
    image: ${APP_IMAGE:-}
    command: sh -c 'bun migrate:db && bun dev'
    restart: always
    container_name: backend
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - ../src:/app/src
      - ../migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "${APP_PORT:-8080}"

  db:
    image: postgres:16-alpine
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    expose:
      - "${POSTGRES_PORT:-5432}"
    command: -p "${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT:-5432} -h ${POSTGRES_HOST}"]
      interval: 5s
      timeout: 5s
      retries: 5
